 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
  <body>         
<div class="sidebar">
            <ul class="nav nav-pills nav-stacked">
            <?php if ($_navs) {?>
              <?php foreach ($_navs as $key => $nav) {?>
                <li data-module="<?=$nav['module']?>">
                  <?php if ($nav['subnavs']) {?>
                    <a data-toggle="collapse" href="#nav-collapse-<?=$key?>"><i class="icon icon-<?=$nav['icon']?>"></i><?=$nav['text']?></a>
                    <div class="collapse" id="nav-collapse-<?=$key?>">
                      <ul class="nav-nested" role="menu">
                        <?php foreach ($nav['subnavs'] as $subNav){ ?>
                        <li data-module="<?=$subNav['module']?>" role="presentation"><a href="<?=$urlPrefix?><?=$subNav['url']?>"><?=$subNav['text']?></a></li>
                        <?php }?>
                      </ul>
                    </div>
                  <?php } else {?>
                    <a href="<?=$urlPrefix?><?=$nav['url']?>"><i class="icon icon-<?=$nav['icon']?>"></i><?=$nav['text']?></a>
                  <?php } ?>
                </li>
              <?php } ?>
            <?php } ?>
           </ul>
          </div>
