<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <title><?=$_title?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/all.css">
        <!--<script data-main="/js/all" src="/js/require.js"></script>-->

        <script src="/js/jquery.js"></script>
        <script src="/js/underscore.js"></script>
        <script src="/js/bootstrap.js"></script>
        <script src="/js/ZeroClipboard.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 10]>
        <p class="browsehappy">您正在使用一款<strong>老旧的</strong>浏览器，本网站的部分功能可能无法正常使用。请<a href="http://browsehappy.com/">更新您的浏览器</a>以改善您的体验。</p>
        <![endif]-->

        <header class="header">
        <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar-collapse">
                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$urlPrefix?>">测试网站Boss中心</a>
                <!-- <a class="navbar-brand text-hide" href="<?=$urlPrefix?>">点评微生活商户中心</a> -->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="header-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <?php if ($_user){ ?>
                    <li class="welcome">
                    <span>欢迎您</span>
                    <span><?=$_user['mName']?></span>
                    <a href="<?=$_baseUri?>/index/logout">退出</a>
                    </li>
                    <?php } ?>
                    <!--
                    <li>
                    <a href="index.html" title="首页">
                        <i class="icon icon-blue-house"></i>
                        <span class="nav-text">首页</span>
                    </a>
                    </li>
                    <li>
                    <a href="#" title="设置">
                        <i class="icon icon-blue-gear"></i>
                        <span class="nav-text">设置</span>
                    </a>
                    </li>
                    <li>
                    <a href="#" title="帮助">
                        <i class="icon icon-blue-query"></i>
                        <span class="nav-text">帮助</span>
                    </a>
                    </li>
                    -->
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
        </nav>
        </header>
        <!-- end header -->
