          <div class="sidebar">
            <ul class="nav nav-pills nav-stacked">
            <?php if ($_navs) {?>
              <?php foreach ($_navs as $key => $nav) {?>
                <li data-module="<?=$nav['module']?>">
                  <?php if ($nav['subnavs']) {?>
                    <a data-toggle="collapse" href="#nav-collapse-<?=$key?>"><i class="icon icon-<?=$nav['icon']?>"></i><?=$nav['text']?></a>
                    <div class="collapse" id="nav-collapse-<?=$key?>">
                      <ul class="nav-nested" role="menu">
                        <?php foreach ($nav['subnavs'] as $subNav){ ?>
                        <li data-module="<?=$subNav['module']?>" role="presentation"><a href="<?=$urlPrefix?><?=$subNav['url']?>"><?=$subNav['text']?></a></li>
                        <?php }?>
                      </ul>
                    </div>
                  <?php } else {?>
                    <a href="<?=$urlPrefix?><?=$nav['url']?>"><i class="icon icon-<?=$nav['icon']?>"></i><?=$nav['text']?></a>
                  <?php } ?>
                </li>
              <?php } ?>
            <?php } ?>
           </ul>
          </div>
<script>
$(function(){
    var href = window.location.href;
    var index = href.indexOf('?');
    if (index != -1) {
        href = href.substr(0, index);
    }

    index = href.indexOf('#');
    if (index != -1) {
        href = href.substr(0, index);
    }

    $('.sidebar').find(".nav > li").each(function () {
        var tgl = $(this).find("a").data('toggle');
        var pHref = $(this).find("a").prop('href');
        if(typeof(tgl) == 'undefined') {
           //只有一个链接 
           if (href==pHref){
                $(this).addClass('active');
           } 
        } else {
            var isActive = false;
            $(this).find("div > ul > li").each(function(){
                var navHref = $(this).find("a").prop('href');
                if (navHref == href) {
                    isActive = true;
                    $(this).addClass('active');
                }
            })
            if (isActive) {
                $(this).addClass("open");
                $(this).find("> a").removeClass("collapsed");
                $(this).find("div").addClass("in");
            }
        }
    
    });
    $('.sidebar').find(".nav > li").click(function(){
        if ($(this).hasClass("open")) {
            $(this).removeClass("open");
        } else {
            $(this).addClass("open");
        }
    });
})
</script>
