<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
  <body>
<?php require __DIR__ . '/../base/sidebar.phtml' ?>
<input type="button" value="退出登陆" onclick="javascript:window.location.href='/pos/index/logout';"><br/>
<form method="post">

商品名称:<input name="gLineCode" type="text" value="<?=$params['gLineCode']?>"><input type="button" value="获取商品属性" id="getGoods"><br/>
会员卡号:<input name="uNo" type="text" value="<?=$params['uNo']?>"><input type="button" value="获取用户信息" id="getUser" ><br/>

    <input  type="submit" value="消费"><br/>
</form>
<br/>

<script>
$('#getGoods').click(function(){
    $.post('/pos/user/getGoods', {gLineCode:$('input[name=gLineCode]').val()}, function(data){
        if (data.errcode == 0) {
            alert('ok');
        } else {
            alert(data.errmsg);
        }
    }, 'json');
});
$('#getUser').click(function(){
    $.post('/pos/user/getUser', {uNo:$('input[name=uNo]').val(),gLineCode:$('input[name=gLineCode]').val()}, function(data){
        if (data.errcode == 0) {
            alert('yes');
        } else {
            alert(data.errmsg)
        }
    }, 'json');
});
</script>
</body>
</html>
