<?php require __DIR__ . '/../base/header.phtml' ?>
<div class="main">
            <div class="container">
                <div class="main-header">
                    <h4 class="main-title">
                        <i class="icon icon-house"></i>
                        <span>商家-名称</span>
                    </h4>
                   <?php if ($_breadcrumb){?>
                    <ol class="breadcrumb">
                        <?php foreach($_breadcrumb as $bread){ ?>
                        <li <?php if ($bread['active']){echo 'class="active"';}?> >
<?php if (!$bread['active']){ ?>
<a href="<?php if($bread['url']){echo $bread['url'];}else{echo "javascript:void(0);";}?>"><?=$bread['text']?></a><?php } else {?><?=$bread['text']?>
<?php }?>
</li>
                        <?php }?>
                    </ol>
                    <?php }?>
                </div>
                <div class="main-content">

<?php require __DIR__ . '/../base/sidebar.phtml' ?>
<div class="mainbody">
                        <div class="panel panel-default we-panel">
                            <div class="panel-heading">
                            <h3 class="panel-title"><?=array_pop($_breadcrumb)['text']?></h3>
                            </div>
                            <div class="panel-body">

    <a href="add"><input  type="button" value="添加"></a><br/>
<form method="get">

用户名:<input name="uName" type="text" value="<?=$params['uName']?>"><br/>

    <input  type="submit" value="查询"><br/>
</form>
<br/>
<table>
<tr>
<td>用户名</td>
<td>手机号</td>
<td>操作</td>
</tr>
<?php if($list) {?>
<?php foreach ($list as $data){?>
<tr>
<td><?=$data->uName?></td>
<td><?=$data->uPhone?></td>
<td><a href="edit?id=<?=$data->uid?>">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="remove?id=<?=$data->uid?>">删除</a></td>
</tr>
<?php }?>
<?php }?>
<tr>
<td colspan=3><?=$links['all']?>|总记录数<?=$totalItems?>条</td>
</tr>
</table>



<!-- 模态弹窗：重置密码成功 -->
                                <div class="modal fade we-modal-confirm account-reset-success-modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-sm">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <h4><i class="icon icon-success"></i>重置密码成功！</h4>
                                                <p>帐号和密码已发送短信至该用户绑定的手机上！</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button class="btn btn-primary we-btn" type="button" data-dismiss="modal">确认</button>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- /.modal -->


</div><!-- /.panel-body -->
                        </div><!-- /.panel -->
                    </div><!-- /.mainbody -->
                </div>
            </div>
        </div>
<?php require __DIR__ . '/../base/footer.phtml' ?>
