<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
  <body>
<?php require __DIR__ . '/../base/sidebar.phtml' ?>
    <a href="add"><input  type="button" value="添加"></a><br/>
<form method="get">

商品名称:<input name="gName" type="text" value="<?=$params['gName']?>"><br/>

    <input  type="submit" value="查询"><br/>
</form>
<br/>
<table>
<tr>
<td>商品名称</td>
<td>商品类型</td>
<td>操作</td>
</tr>
<?php if($list) {?>
<?php foreach ($list as $data){?>
<tr>
<td><?=$data->gName?></td>
<td><?=$types[$data->gType]?></td>
<td><a href="edit?id=<?=$data->gid?>">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="remove?id=<?=$data->gid?>">删除</a></td>
</tr>
<?php }?>
<?php }?>
<tr>
<td colspan=3><?=$links['all']?>|总记录数<?=$totalItems?>条</td>
</tr>
</table>
</body>
</html>
