<?php require __DIR__ . '/../base/sidebar.phtml' ?>
<form method="post">
    用户名:<input name="mName" type="text"><br/>
    密码:<input name="mPwd" type="password"><br/>
    手机号:<input name="mPhone" type="text" ><br/>
    <input name="mid" type="hidden" value="<?=$data->mid?>"><br/>
    <input  type="submit" value="<?php if ($action == 'add') { echo '添加';} else {echo '编辑';}?>"><br/>
</form>
</body>
</html>
