<?php require __DIR__ . '/../base/sidebar.phtml' ?>
    <a href="add"><input  type="button" value="添加"></a><br/>
<form method="get">

用户名:<input name="cName" type="text" value="<?=$params['cName']?>"><br/>
手机号:<input name="cPhone" type="text" value="<?=$params['cPhone']?>"><br/>

    <input  type="submit" value="查询"><br/>
</form>
<br/>
<table>
<tr>
<td>用户名</td>
<td>手机号</td>
<td>操作</td>
</tr>
<?php if($list) {?>
<?php foreach ($list as $data){?>
<tr>
<td><?=$data->cName?></td>
<td><?=$data->cPhone?></td>
<td><a href="edit?id=<?=$data->cid?>">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="remove?id=<?=$data->cid?>">删除</a></td>
</tr>
<?php }?>
<?php }?>
<tr>
<td colspan=3><?=$links['all']?>|总记录数<?=$totalItems?>条</td>
</tr>
</table>
</body>
</html>
