<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
  <body>
<?php require __DIR__ . '/../base/sidebar.phtml' ?>
<form method="post">
用户名:<input name="rName" type="text" value="<?=$data->rName?>"><br/>
    密码:<input name="rPwd" type="password" value="<?=$data->rPwd?>"><br/>
    手机号:<input name="rPhone" type="text"  value="<?=$data->rPhone?>"><br/>
    售卡类型:<select name="rType" ><?php foreach($types as $type => $desc){?> <option value="<?=$type?>" <?php if($data->rType == $type){echo "selected";}?>><?=$desc?></option> <?php }?> </select><br/>
    销售分成:<input name="rSaleRate" type="text"  value="<?=$data->rSaleRate / $rateMultiple?>"><br/>
    售卡分成:<input name="rSaleCardRate" type="text"  value="<?=$data->rSaleCardRate / $rateMultiple?>"><br/>
    <input name="rid" type="hidden" value="<?=$data->rid?>"><br/>
    <input  type="submit" value="<?php if ($action == 'add') { echo '添加';} else {echo '编辑';}?>"><br/>
</form>
</body>
</html>
